import numpy as np
import sys
from tensorflow.python.keras import backend as K
from tensorflow.python.keras.models import Model
from tensorflow.python.keras.layers import Flatten, Dense, Dropout
from tensorflow.python.keras.applications.resnet50 import ResNet50, preprocess_input
from tensorflow.python.keras.optimizers import Adam
from tensorflow.python.keras.preprocessing.image import ImageDataGenerator
PROJECT_DIR = "/tf/Hutomize/"
sys.path.append(PROJECT_DIR)

def random_crop(img, random_crop_size):
    # Note: image_data_format is 'channel_last'
    assert img.shape[2] == 3
    height, width = img.shape[0], img.shape[1]
    dy, dx = random_crop_size
    x = np.random.randint(0, width - dx + 1)
    y = np.random.randint(0, height - dy + 1)
    return img[y:(y+dy), x:(x+dx), :]


def crop_generator(batches, crop_length):
    """Take as input a Keras ImageGen (Iterator) and generate random
    crops from the image batches generated by the original iterator.
    """
    while True:
        batch_x, batch_y = next(batches)
        batch_crops = np.zeros((batch_x.shape[0], crop_length, crop_length, 3))
        batch_crops_y = np.zeros((batch_x.shape[0], crop_length, crop_length, 3))
        for i in range(batch_x.shape[0]):
            batch_crops[i] = random_crop(batch_x[i], (crop_length, crop_length))
            batch_crops_y[i] = batch_crops[i]
            gaus = np.random.normal(loc=0,scale=0.2, size =(224,224,3))
            batch_crops[i] = batch_crops[i] + gaus
            
            batch_crops[i] = np.clip(batch_crops[i],0,1)

        yield (batch_crops, batch_crops_y)

class SurgicalDataset(object):
    def __init__(self, data_path = ''):
        BATCH_SIZE = 60
        print ('batch SIZE', BATCH_SIZE)
        self.dataPath = data_path
        self.dataGenerator = ImageDataGenerator(rescale = 1./255.)
        train_dir = PROJECT_DIR + 'data2/'
        print("Train Directory: " + train_dir)
        train_datagen = ImageDataGenerator(rescale=1./255)

        train_generator = train_datagen.flow_from_directory(train_dir,shuffle=True, batch_size=BATCH_SIZE, target_size=(256, 320), color_mode='rgb', class_mode='input')
        self.data = crop_generator(train_generator, 224)
        
    def getIterator(self):
        return self.data
    



